url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Adyan Muhammad" # the name of your site, e.g. ACME Corp.

collections:
  - projects

kramdown:
  syntax_highlighter: rouge  